### ISSUE TITLE
GIF Banners return a static PNG image

### ISSUE THREAD

**Issue by Robonics** [Tolfx/discord-banner#2]
Using discord-banner version 1.6.7

Expected Behavior:
Using `user.bannerURL()` on a user who has a GIF banner will return the gif URL if the `{dynamic: true}` option is passed, similar to `avatarURL()`

Resulting Behavior:
Image is always a static PNG, regardless of any options passed

**Comment by Tolfx** [comment]
Because option `dynamic` isn't a option.
Use `{ format: 'gif' }` instead.
